spring:
  application:
    name: service-consumer

server:
  port: 8090

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost2:8761/eureka/,http://localhost3:8762/eureka/