eureka:
  client:
    service-url:
      defaultZone: http://localhost2:8761/eureka/,http://localhost3:8762/eureka/

---
spring:
  profiles: 8761
  application:
    name: eureka-server-1

server:
  port: ${spring.profiles}

eureka:
  instance:
    hostname: localhost2

---
spring:
  profiles: 8762
  application:
    name: eureka-server-2

server:
  port: ${spring.profiles}

eureka:
  instance:
    hostname: localhost3
